
#type: args


path:
  dataset_path: '/home/oem/ntthu/hiepnh/RATD/data/ts2vec'
  encoder_path: './TCN-master/training/electricity__test1_20240421_163624/model.pt'
  vec_train_path: './data/TCN/ele_trainvec_list.pt'
  vec_val_path: './data/TCN/ele_valvec_list.pt'
  vec_test_path: './data/TCN/ele_testvec_list.pt'
  ref_train_path: './data/TCN/ele_train_id_list.pt'
  ref_val_path: './data/TCN/ele_val_id_list.pt'
  ref_test_path: './data/TCN/ele_test_id_list.pt'
  diffusion_embedding_dim: 128
  beta_start: 0.0001
  beta_end: 0.5
  num_steps: 50
  schedule: "quad"
  is_linear: True

retrieval:
  device: 'cuda:1'
  H: 168  # hoziron (pred_len)
  L: 96  # his_len
  length: 26305
  num_channels: 400
  level: 3  #top_k
  num_sample_features: 64
  use_reference: True
